### ISSUE TITLE
Cannot turn off header scaling/non-monospace font

### ISSUE THREAD

**Issue by alcesleo** [jrblevin/markdown-mode#151]
I'm having issues with displaying headers, I would like them to be the same font as the rest of the document, and not be scaled (since this doesn't seem to work together with zoom-frm, they just stay the same size) but even though I've set `markdown-header-scaling` to `nil` it doesn't seem to work.

Any ideas?

**Comment by jrblevin** [comment]
There are two things you'll need to change:
1. The face (font) is independent of scaling. You can customize the face by setting `markdown-header-face`. By default, it inherits from `variable-pitch` so you'd probably want to change it to inherit from `default'.
2. Scaling, similarly, is independent of the header face. You should indeed set `markdown-header-scaling` to `nil`. If you did this in your init file, outside of the `M-x customize` interface, then you'll probably have to restart Emacs for it to take effect.

**Comment by alcesleo** [comment]
Thanks for your help! Step 1 works perfectly, but I can't get step 2 to work. I've restarted emacs, set it both in my config and through customize but it won't stop scaling them...

**Comment by jrblevin** [comment]
That's strange. Changing the scaling should be immediate if done through the customize interface.

Is it possible that the header faces have been customized elsewhere? One thing you can do is to try to force the update by issuing `M-: (markdown-update-header-faces)`. With nil arguments, it should turn off scaling. Then inspect the header faces using `describe-face`. The face names are `markdown-header-face-1` to `markdown-header-face-6`. You can check the height and other properties to make sure they aren't picking up properties from elsewhere.

Also, just to set the record straight for future reference, I was wrong about the scaling and face being fully independent. After checking the code, if `markdown-header-scaling` is nil, the header faces also do not inherit from `variable-pitch`.

**Comment by alcesleo** [comment]
It seems like the heights are set to specific values somehow... This is what I get from `describe-face`

```
Face: markdown-header-face-2 (sample) (customize this face)

Documentation:
Face for level 2 headers.

You probably don't want to customize this face directly. Instead
you can customize the base face `markdown-header-face' or the
variable-height variable `markdown-header-scaling'.

Defined in `markdown-mode.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: 150
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: markdown-header-face
```

```
Face: markdown-header-face (sample) (customize this face)

Documentation:
Base face for headers.

Defined in `markdown-mode.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: default
```
