### ISSUE TITLE
Wrong fontification of indented YAML and TOML metadata

### ISSUE THREAD

**Issue by saf-dmitry** [jrblevin/markdown-mode#476]
Indended statements in YAML and TOML metadata blocks

```
---
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose
    nucleic acid'
---
```

 are not fontified as such.

## Software Versions

- Markdown Mode: From Git on 2020-05-06
- Emacs: 26.3
- OS: macOS 10.14.6

## Solution

Since both YAML and TOML metadata statements can be indented using tabs and/or spaces (common in YAML to indicate nesting, allowed, but not required in TOML), the regexp `markdown-regex-declarative-metadata` should be modified as follows to allow tabs and/or spaces at BOL:

```elisp
(defconst markdown-regex-declarative-metadata
  "^[ \t]*\\([[:alpha:]][[:alpha:] _-]*?\\)\\([:=][ \t]*\\)\\(.*\\)$"
  "Regular expression for matching declarative metadata statements.
This matches MultiMarkdown metadata as well as YAML and TOML
assignments such as the following:

    variable: value

or

    variable = value")
```
